import { useTranslations } from "next-intl";
import { memo } from "react";
import { Button } from "./ui/button";
import { Icons } from "./icons";

export const FBShare = memo(function FBShare({
  imageUrl,
  text,
}: {
  imageUrl: string | null | undefined;
  text: string;
}) {
  const t = useTranslations("social");
  const handleShareClick = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${imageUrl}&title=${text}&caption=${text}&description=${text}`;
    window.open(url, "_blank");
  };

  return (
    <Button
      size="xs"
      disabled={!imageUrl}
      type="button"
      onClick={handleShareClick}
    >
      <Icons.fb className="mr-2 h-4 w-4" />
      {t("shareOnFacebook")}
    </Button>
  );
});

export const XPost = memo(function XPost({ text }: { text: string }) {
  const t = useTranslations("social");
  if (!text) {
    return null;
  }

  return (
    <>
      <a
        className="twitter-share-button inline-flex items-center justify-center rounded-md border bg-background px-2 py-1 text-sm font-medium text-primary shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
        href="https://twitter.com/share?ref_src=twsrc%5Etfw"
        data-text={`${text} - generated by AIstein.cz`}
        data-show-count="false"
        onClick={(event) => {
          if (!text) return;
          event.preventDefault();
        }}
      >
        {t("shareOnTwitter")}
      </a>
      <script async src="https://platform.twitter.com/widgets.js" />
    </>
  );
});
